

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    url: jdbc:mysql://localhost:3306/demo_security?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  redis:
    host: 127.0.0.1


jwt:
  secret: "secret"
  redis-key:
    user: 'user:'
    jwt: 'jwt:'

